from table_data import TableData

WEAPON = TableData("Weapon", normalize=True)
WEAPON.add_item("Dagger", 0, 0, [])
WEAPON.add_item("Quarterstaff", 0, 0, [])
WEAPON.add_item("Spear", 0, 0, [])
WEAPON.add_item("Longspear", 0, 0, [])
WEAPON.add_item("Blowgun", 0, 0, [])
WEAPON.add_item("Heavy Crossbow", 0, 0, [])
WEAPON.add_item("Light Crossbow", 0, 0, [])
WEAPON.add_item("Dart x10", 0, 0, [])
WEAPON.add_item("Javelin", 0, 0, [])
WEAPON.add_item("Sling", 0, 0, [])
WEAPON.add_item("Gauntlet", 0, 0, [])
WEAPON.add_item("Cestus", 0, 0, [])
WEAPON.add_item("Punching Dagger", 0, 0, [])
WEAPON.add_item("Spiked Gauntlet", 0, 0, [])
WEAPON.add_item("Light Mace", 0, 0, [])
WEAPON.add_item("Sickle", 0, 0, [])
WEAPON.add_item("Club", 0, 0, [])
WEAPON.add_item("Heavy Mace", 0, 0, [])
WEAPON.add_item("Morningstar", 0, 0, [])
WEAPON.add_item("Shortspear", 0, 0, [])
WEAPON.add_item("Gladius", 0, 0, [])
WEAPON.add_item("Handaxe", 0, 0, [])
WEAPON.add_item("Jutte", 0, 0, [])
WEAPON.add_item("Kerambit", 0, 0, [])
WEAPON.add_item("Kukri", 0, 0, [])
WEAPON.add_item("Light hammer", 0, 0, [])
WEAPON.add_item("Light pick", 0, 0, [])
WEAPON.add_item("Sap", 0, 0, [])
WEAPON.add_item("Shortsword", 0, 0, [])
WEAPON.add_item("Throwing axe", 0, 0, [])
WEAPON.add_item("Battleaxe", 0, 0, [])
WEAPON.add_item("Heavy Pick", 0, 0, [])
WEAPON.add_item("Light Flail", 0, 0, [])
WEAPON.add_item("Longsword", 0, 0, [])
WEAPON.add_item("Broadsword", 0, 0, [])
WEAPON.add_item("Rapier", 0, 0, [])
WEAPON.add_item("Scimitar", 0, 0, [])
WEAPON.add_item("Scizore", 0, 0, [])
WEAPON.add_item("Trident", 0, 0, [])
WEAPON.add_item("Warhammer", 0, 0, [])
WEAPON.add_item("Bardiche", 0, 0, [])
WEAPON.add_item("Falchion", 0, 0, [])
WEAPON.add_item("Glaive", 0, 0, [])
WEAPON.add_item("Greataxe", 0, 0, [])
WEAPON.add_item("Greatclub", 0, 0, [])
WEAPON.add_item("Greatsword", 0, 0, [])
WEAPON.add_item("Halberd", 0, 0, [])
WEAPON.add_item("Heavy Flail", 0, 0, [])
WEAPON.add_item("Lance", 0, 0, [])
WEAPON.add_item("Scythe", 0, 0, [])
WEAPON.add_item("Chakram", 0, 0, [])
WEAPON.add_item("Composite Longbow", 0, 0, [])
WEAPON.add_item("Composite Shortbow", 0, 0, [])
WEAPON.add_item("Longbow", 0, 0, [])
WEAPON.add_item("Shortbow", 0, 0, [])
WEAPON.add_item("Pilum", 0, 0, [])
WEAPON.add_item("Atlatl", 0, 0, [])
WEAPON.add_item("Fighting Fan", 0, 0, [])
WEAPON.add_item("Sai", 0, 0, [])
WEAPON.add_item("Aklys", 0, 0, [])
WEAPON.add_item("Scorpion Whip", 0, 0, [])
WEAPON.add_item("Nunchaku", 0, 0, [])
WEAPON.add_item("Swordbreaker", 0, 0, [])
WEAPON.add_item("Bastard Sword", 0, 0, [])
WEAPON.add_item("Dwarven Waraxe", 0, 0, [])
WEAPON.add_item("Hooked Axe", 0, 0, [])
WEAPON.add_item("Katana", 0, 0, [])
WEAPON.add_item("Whip", 0, 0, [])
WEAPON.add_item("Dire Flail", 0, 0, [])
WEAPON.add_item("Dwarven urgrosh", 0, 0, [])
WEAPON.add_item("Elven curve blade", 0, 0, [])
WEAPON.add_item("Harpoon", 0, 0, [])
WEAPON.add_item("Orc double axe", 0, 0, [])
WEAPON.add_item("Spiked chain", 0, 0, [])
WEAPON.add_item("Net", 0, 0, [])
WEAPON.add_item("Two Bladed Sword", 0, 0, [])
WEAPON.add_item("Gnome hooked hammer", 0, 0, [])
WEAPON.add_item("Boomerang", 0, 0, [])
WEAPON.add_item("Bolas", 0, 0, [])
WEAPON.add_item("Hand crossbow", 0, 0, [])
WEAPON.add_item("Lasso", 0, 0, [])
WEAPON.add_item("Repeating heavy crossbow", 0, 0, [])
WEAPON.add_item("Repeating light crossbow", 0, 0, [])
WEAPON.add_item("Shuriken x5", 0, 0, [])


MAGIC_WEAPON = TableData("Magic Weapon", magic=True, normalize=True)

WEAPON_CHECK = TableData("Weapon Magic/Mundane")
WEAPON_CHECK.add_item("Mundane", 1, 90, [WEAPON])
WEAPON_CHECK.add_item("Magic", 91, 100, [MAGIC_WEAPON])
