from table_data.table_data import TableData

POTION2 = TableData("Potion2", normalize=True, final=True)
POTION2.add_item("Barkskin +3", 0, 0, [])

POTION = TableData("Potion", ext=True, normalize=True, final=True)
POTION.add_item("Potion of Cure light wounds", 0, 0, [])
POTION.add_item("Potion of Endure elements", 0, 0, [])
POTION.add_item("Potion of Hide from animals", 0, 0, [])
POTION.add_item("Potion of Hide from undead", 0, 0, [])
POTION.add_item("Potion of Jump", 0, 0, [])
POTION.add_item("Potion of Mage armor", 0, 0, [])
POTION.add_item("Potion of Magic fang", 0, 0, [])
POTION.add_item("Potion of Magic stone", 0, 0, [])
POTION.add_item("Potion of Magic weapon", 0, 0, [])
POTION.add_item("Potion of Pass without trace", 0, 0, [])
POTION.add_item("Potion of Protection from Good", 0, 0, [])
POTION.add_item("Potion of Protection from Evil", 0, 0, [])
POTION.add_item("Potion of Remove fear", 0, 0, [])
POTION.add_item("Potion of Sanctuary", 0, 0, [])
POTION.add_item("Potion of Shield of faith +2", 0, 0, [])
POTION.add_item("Potion of Shillelagh", 0, 0, [])
POTION.add_item("Potion of Bless Weapon", 0, 0, [])
POTION.add_item("Potion of Enlarge person", 0, 0, [])
POTION.add_item("Potion of Reduce person", 0, 0, [])
POTION.add_item("Potion of Aid", 0, 0, [])
POTION.add_item("Potion of Barkskin +2", 0, 0, [])
POTION.add_item("Potion of Bear's Endurance", 0, 0, [])
POTION.add_item("Potion of Blur", 0, 0, [])
POTION.add_item("Potion of Bull's strength", 0, 0, [])
POTION.add_item("Potion of Cat's grace", 0, 0, [])
POTION.add_item("Potion of Cure moderate wounds", 0, 0, [])
POTION.add_item("Potion of Darkness", 0, 0, [])
POTION.add_item("Potion of Darkvision", 0, 0, [])
POTION.add_item("Potion of Delay poison", 0, 0, [])
POTION.add_item("Potion of Eagle's splendor", 0, 0, [])
POTION.add_item("Potion of Fox's cunning", 0, 0, [])
POTION.add_item("Potion of Invisibility", 0, 0, [])
POTION.add_item("Potion of Lesser restoration", 0, 0, [])
POTION.add_item("Potion of Levitate", 0, 0, [])
POTION.add_item("Potion of Misdirection", 0, 0, [])
POTION.add_item("Potion of Owl's Wisdom", 0, 0, [])
POTION.add_item("Potion of Protection from arrows (30)", 0, 0, [])
POTION.add_item("Potion of Remove Paralysis", 0, 0, [])
POTION.add_item("Potion of Resist Energy", 0, 0, [])
POTION.add_item("Potion of Shield of faith +3", 0, 0, [])
POTION.add_item("Potion of Spider climb", 0, 0, [])
POTION.add_item("Potion of Undetectable Alignment", 0, 0, [])
#POTION.add_item("Level 2 Potion", 0, 0, [POTION2])
